# Gin-Vue-Admin Global Configuration

# casbin configuration
casbin:
    model-path: './resource/rbac_model.conf'

# jwt 签名密钥
jwt:
    signing-key: 'personServerAdmin'

# mysql 连接配置
mysql:
    username: root
    password: 'Tt15978096339'
    path: '127.0.0.1:3333'
    db-name: 'test'
    config: 'charset=utf8&parseTime=True&loc=Local'
    max-idle-conns: 20
    max-open-conns: 20
    log-mode: false

# oss configuration

# redis configuration
redis:
    addr: '127.0.0.1:6379'
    password: ''
    db: 0

# system configuration MAX 65535
system:
    use-multipoint: true
    env: 'public'  # Change to "develop" to skip authentication for development mode
    addr: 10086
    db-type: "mysql"  # support mysql(mariaDb)

# captcha configuration
captcha:
    key-long: 6
    img-width: 240
    img-height: 80

# logger 
#level:panic fatal error warn info debug trace
log:
    log-file: true
    level: 'debug'
    file: 'serverLog'